"""simplify users table

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-22 12:29:00.993903

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_last_edited_by_users"), "users", type_="foreignkey")
    op.drop_column("users", "last_edited_at")
    op.drop_column("users", "last_edited_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_edited_by", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "last_edited_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_users_last_edited_by_users"),
        "users",
        "users",
        ["last_edited_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
