"""pick'em data model — team, week, game, pick

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-22 20:13:00.000000

Hand-written (not blindly autogenerated) so the two Postgres partial unique
indexes on ``pick`` — which Alembic autogenerate would miss — are included, and
so the three native enum types are created/dropped deterministically.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql  # noqa: F401  (kept for parity with 0003)

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Parents before children (FK dependency order): team, week, game, pick.
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("espn_team_id", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("espn_team_id", name="uq_team_espn_team_id"),
    )

    op.create_table(
        "week",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("window_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lines_frozen", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season", "week", name="uq_week_season_week"),
    )

    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("espn_event_id", sa.Integer(), nullable=False),
        sa.Column("espn_competition_id", sa.Integer(), nullable=True),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "IN_PROGRESS", "FINAL", name="gamestatus"),
            nullable=False,
        ),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("spread", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("total", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("favorite_team_id", sa.Integer(), nullable=True),
        sa.Column("underdog_team_id", sa.Integer(), nullable=True),
        sa.Column("odds_provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("odds_frozen", sa.Boolean(), nullable=False),
        sa.Column("odds_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("espn_event_id", name="uq_game_espn_event_id"),
        sa.ForeignKeyConstraint(["week_id"], ["week.id"], name="fk_game_week_id_week"),
        sa.ForeignKeyConstraint(["home_team_id"], ["team.id"], name="fk_game_home_team_id_team"),
        sa.ForeignKeyConstraint(["away_team_id"], ["team.id"], name="fk_game_away_team_id_team"),
        sa.ForeignKeyConstraint(
            ["favorite_team_id"], ["team.id"], name="fk_game_favorite_team_id_team"
        ),
        sa.ForeignKeyConstraint(
            ["underdog_team_id"], ["team.id"], name="fk_game_underdog_team_id_team"
        ),
    )

    op.create_table(
        "pick",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column(
            "pick_type",
            sa.Enum("UNDERDOG_COVER", "FAVORITE_COVER", "OVER", "UNDER", name="picktype"),
            nullable=False,
        ),
        sa.Column("is_mortal_lock", sa.Boolean(), nullable=False),
        sa.Column("result", sa.Enum("PENDING", "WIN", "LOSS", name="pickresult"), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_pick_user_id_users"),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], name="fk_pick_game_id_game"),
        sa.ForeignKeyConstraint(["week_id"], ["week.id"], name="fk_pick_week_id_week"),
    )
    # Partial unique indexes (Postgres ``WHERE`` predicate) — DB-level enforcement
    # of the per-user/week invariants. Autogenerate would not emit these.
    op.create_index(
        "uq_pick_user_week_type_base",
        "pick",
        ["user_id", "week_id", "pick_type"],
        unique=True,
        postgresql_where=sa.text("is_mortal_lock = false"),
    )
    op.create_index(
        "uq_pick_user_week_mortal_lock",
        "pick",
        ["user_id", "week_id"],
        unique=True,
        postgresql_where=sa.text("is_mortal_lock = true"),
    )


def downgrade() -> None:
    # Reverse order, FK-safe: indexes, then child→parent tables, then enum types.
    op.drop_index("uq_pick_user_week_mortal_lock", table_name="pick")
    op.drop_index("uq_pick_user_week_type_base", table_name="pick")
    op.drop_table("pick")
    op.drop_table("game")
    op.drop_table("week")
    op.drop_table("team")

    # Drop the native enum types created implicitly by the ``sa.Enum(name=...)``
    # columns above. ``checkfirst`` keeps the downgrade idempotent.
    bind = op.get_bind()
    sa.Enum(name="pickresult").drop(bind, checkfirst=True)
    sa.Enum(name="picktype").drop(bind, checkfirst=True)
    sa.Enum(name="gamestatus").drop(bind, checkfirst=True)
